// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
const SUPABASE_PROJECT_REF = SUPABASE_URL ? new URL(SUPABASE_URL).hostname.split(".")[0] : null;

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
export const supabaseConfigError =
  "Falta configurar VITE_SUPABASE_URL y VITE_SUPABASE_ANON_KEY en el entorno de despliegue.";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const getSupabaseAuthStorageKey = () => {
  if (!SUPABASE_PROJECT_REF) return null;
  return `sb-${SUPABASE_PROJECT_REF}-auth-token`;
};

if (typeof window !== "undefined" && window.location.pathname === "/login") {
  const authStorageKey = getSupabaseAuthStorageKey();
  if (authStorageKey) {
    window.localStorage.removeItem(authStorageKey);
  }
}

export const supabase = createClient<Database>(
  SUPABASE_URL || "https://placeholder.supabase.co",
  SUPABASE_PUBLISHABLE_KEY || "placeholder-anon-key",
  {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
  }
);

export const clearSupabaseAuthStorage = () => {
  if (typeof window === "undefined" || !SUPABASE_PROJECT_REF) return;

  const authStorageKey = getSupabaseAuthStorageKey();
  if (!authStorageKey) return;

  window.localStorage.removeItem(authStorageKey);
};
